baseurl = "https://kshitijsrivastava.com/"
title = "Kshitij Srivastava"
author = "Kshitij Srivastava"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "Kshitij Srivastava"
copyright = "© 2018 Kshitij Srivastava"
copyrightUrl = "https://kshitijsrivastava.com/"
faviconfile = "image/favicon1.png"
logofile = "image/kshitij.jpg"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "kshitij0987"
twitter = "7shitij"
linkedin = "kshitij-srivastava-ds"
email = "ksrivastava34@gatech.edu"

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
