baseurl = "https://kshitijsrivastava.com/"
title = "Kshitij Srivastava"
author = "Kshitij Srivastava"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

googleAnalytics = "UA-138240838-1"
disqusShortname = "datageek1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "Kshitij Srivastava"
copyright = "© 2019 Kshitij Srivastava"
copyrightUrl = "https://kshitijsrivastava.com/"
faviconfile = "image/favicon1.png"
logofile = "image/kshitij.jpg"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "kshitij0987"
twitter = "7shitij"
linkedin = "kshitij-srivastava-ds"
email = "ksrivastava34@gatech.edu"


[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
